#!/bin/sh

set -e

case "$1" in
    purge)
        rm -rf /var/log/waagent.log* > /dev/null || true
        rm -rf /var/lib/waagent > /dev/null || true
        deluser --quiet --system waagent > /dev/null || true
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
    echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac

#DEBHELPER#

exit 0
