#!/bin/sh
set -e

case "$1" in
    configure)
       if ! getent passwd waagent > /dev/null ; then
           adduser --system --quiet --home /var/lib/waagent --no-create-home --group --gecos "WALinuxAgent" waagent
           install -d --mode=0700 -o waagent -g waagent "/var/lib/waagent"
           touch /var/log/waagent.log
           chown waagent:waagent /var/log/waagent.log
           chmod 644 /var/log/waagent.log
           install -d --mode=0755 -o waagent -g waagent "/var/log/azure"
       fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

